package net.minecraft.client.renderer;

import com.google.common.collect.Maps;
import java.util.Map;
import net.fabricmc.api.EnvType;
import net.fabricmc.api.Environment;
import net.minecraft.client.renderer.chunk.ChunkSectionLayer;
import net.minecraft.client.renderer.rendertype.RenderType;
import net.minecraft.client.renderer.rendertype.RenderTypes;
import net.minecraft.util.Util;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.block.LeavesBlock;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.level.material.Fluid;
import net.minecraft.world.level.material.FluidState;
import net.minecraft.world.level.material.Fluids;

@Environment(EnvType.CLIENT)
public class ItemBlockRenderTypes {
	private static final Map<Block, ChunkSectionLayer> TYPE_BY_BLOCK = Util.make(Maps.newHashMap(), hashMap -> {
		ChunkSectionLayer chunkSectionLayer = ChunkSectionLayer.TRIPWIRE;
		hashMap.put(Blocks.TRIPWIRE, chunkSectionLayer);
		ChunkSectionLayer chunkSectionLayer2 = ChunkSectionLayer.CUTOUT;
		hashMap.put(Blocks.GRASS_BLOCK, chunkSectionLayer2);
		hashMap.put(Blocks.IRON_BARS, chunkSectionLayer2);
		Blocks.COPPER_BARS.forEach(block -> hashMap.put(block, chunkSectionLayer2));
		hashMap.put(Blocks.TRIPWIRE_HOOK, chunkSectionLayer2);
		hashMap.put(Blocks.HOPPER, chunkSectionLayer2);
		hashMap.put(Blocks.IRON_CHAIN, chunkSectionLayer2);
		Blocks.COPPER_CHAIN.forEach(block -> hashMap.put(block, chunkSectionLayer2));
		hashMap.put(Blocks.JUNGLE_LEAVES, chunkSectionLayer2);
		hashMap.put(Blocks.OAK_LEAVES, chunkSectionLayer2);
		hashMap.put(Blocks.SPRUCE_LEAVES, chunkSectionLayer2);
		hashMap.put(Blocks.ACACIA_LEAVES, chunkSectionLayer2);
		hashMap.put(Blocks.CHERRY_LEAVES, chunkSectionLayer2);
		hashMap.put(Blocks.BIRCH_LEAVES, chunkSectionLayer2);
		hashMap.put(Blocks.DARK_OAK_LEAVES, chunkSectionLayer2);
		hashMap.put(Blocks.PALE_OAK_LEAVES, chunkSectionLayer2);
		hashMap.put(Blocks.AZALEA_LEAVES, chunkSectionLayer2);
		hashMap.put(Blocks.FLOWERING_AZALEA_LEAVES, chunkSectionLayer2);
		hashMap.put(Blocks.MANGROVE_ROOTS, chunkSectionLayer2);
		hashMap.put(Blocks.MANGROVE_LEAVES, chunkSectionLayer2);
		hashMap.put(Blocks.OAK_SAPLING, chunkSectionLayer2);
		hashMap.put(Blocks.SPRUCE_SAPLING, chunkSectionLayer2);
		hashMap.put(Blocks.BIRCH_SAPLING, chunkSectionLayer2);
		hashMap.put(Blocks.JUNGLE_SAPLING, chunkSectionLayer2);
		hashMap.put(Blocks.ACACIA_SAPLING, chunkSectionLayer2);
		hashMap.put(Blocks.CHERRY_SAPLING, chunkSectionLayer2);
		hashMap.put(Blocks.DARK_OAK_SAPLING, chunkSectionLayer2);
		hashMap.put(Blocks.PALE_OAK_SAPLING, chunkSectionLayer2);
		hashMap.put(Blocks.WHITE_BED, chunkSectionLayer2);
		hashMap.put(Blocks.ORANGE_BED, chunkSectionLayer2);
		hashMap.put(Blocks.MAGENTA_BED, chunkSectionLayer2);
		hashMap.put(Blocks.LIGHT_BLUE_BED, chunkSectionLayer2);
		hashMap.put(Blocks.YELLOW_BED, chunkSectionLayer2);
		hashMap.put(Blocks.LIME_BED, chunkSectionLayer2);
		hashMap.put(Blocks.PINK_BED, chunkSectionLayer2);
		hashMap.put(Blocks.GRAY_BED, chunkSectionLayer2);
		hashMap.put(Blocks.LIGHT_GRAY_BED, chunkSectionLayer2);
		hashMap.put(Blocks.CYAN_BED, chunkSectionLayer2);
		hashMap.put(Blocks.PURPLE_BED, chunkSectionLayer2);
		hashMap.put(Blocks.BLUE_BED, chunkSectionLayer2);
		hashMap.put(Blocks.BROWN_BED, chunkSectionLayer2);
		hashMap.put(Blocks.GREEN_BED, chunkSectionLayer2);
		hashMap.put(Blocks.RED_BED, chunkSectionLayer2);
		hashMap.put(Blocks.BLACK_BED, chunkSectionLayer2);
		hashMap.put(Blocks.POWERED_RAIL, chunkSectionLayer2);
		hashMap.put(Blocks.DETECTOR_RAIL, chunkSectionLayer2);
		hashMap.put(Blocks.COBWEB, chunkSectionLayer2);
		hashMap.put(Blocks.SHORT_GRASS, chunkSectionLayer2);
		hashMap.put(Blocks.FERN, chunkSectionLayer2);
		hashMap.put(Blocks.BUSH, chunkSectionLayer2);
		hashMap.put(Blocks.DEAD_BUSH, chunkSectionLayer2);
		hashMap.put(Blocks.SHORT_DRY_GRASS, chunkSectionLayer2);
		hashMap.put(Blocks.TALL_DRY_GRASS, chunkSectionLayer2);
		hashMap.put(Blocks.SEAGRASS, chunkSectionLayer2);
		hashMap.put(Blocks.TALL_SEAGRASS, chunkSectionLayer2);
		hashMap.put(Blocks.DANDELION, chunkSectionLayer2);
		hashMap.put(Blocks.OPEN_EYEBLOSSOM, chunkSectionLayer2);
		hashMap.put(Blocks.CLOSED_EYEBLOSSOM, chunkSectionLayer2);
		hashMap.put(Blocks.POPPY, chunkSectionLayer2);
		hashMap.put(Blocks.BLUE_ORCHID, chunkSectionLayer2);
		hashMap.put(Blocks.ALLIUM, chunkSectionLayer2);
		hashMap.put(Blocks.AZURE_BLUET, chunkSectionLayer2);
		hashMap.put(Blocks.RED_TULIP, chunkSectionLayer2);
		hashMap.put(Blocks.ORANGE_TULIP, chunkSectionLayer2);
		hashMap.put(Blocks.WHITE_TULIP, chunkSectionLayer2);
		hashMap.put(Blocks.PINK_TULIP, chunkSectionLayer2);
		hashMap.put(Blocks.OXEYE_DAISY, chunkSectionLayer2);
		hashMap.put(Blocks.CORNFLOWER, chunkSectionLayer2);
		hashMap.put(Blocks.WITHER_ROSE, chunkSectionLayer2);
		hashMap.put(Blocks.LILY_OF_THE_VALLEY, chunkSectionLayer2);
		hashMap.put(Blocks.BROWN_MUSHROOM, chunkSectionLayer2);
		hashMap.put(Blocks.RED_MUSHROOM, chunkSectionLayer2);
		hashMap.put(Blocks.TORCH, chunkSectionLayer2);
		hashMap.put(Blocks.WALL_TORCH, chunkSectionLayer2);
		hashMap.put(Blocks.SOUL_TORCH, chunkSectionLayer2);
		hashMap.put(Blocks.SOUL_WALL_TORCH, chunkSectionLayer2);
		hashMap.put(Blocks.COPPER_TORCH, chunkSectionLayer2);
		hashMap.put(Blocks.COPPER_WALL_TORCH, chunkSectionLayer2);
		hashMap.put(Blocks.FIRE, chunkSectionLayer2);
		hashMap.put(Blocks.SOUL_FIRE, chunkSectionLayer2);
		hashMap.put(Blocks.SPAWNER, chunkSectionLayer2);
		hashMap.put(Blocks.TRIAL_SPAWNER, chunkSectionLayer2);
		hashMap.put(Blocks.VAULT, chunkSectionLayer2);
		hashMap.put(Blocks.WHEAT, chunkSectionLayer2);
		hashMap.put(Blocks.OAK_DOOR, chunkSectionLayer2);
		hashMap.put(Blocks.LADDER, chunkSectionLayer2);
		hashMap.put(Blocks.RAIL, chunkSectionLayer2);
		hashMap.put(Blocks.IRON_DOOR, chunkSectionLayer2);
		hashMap.put(Blocks.REDSTONE_TORCH, chunkSectionLayer2);
		hashMap.put(Blocks.REDSTONE_WALL_TORCH, chunkSectionLayer2);
		hashMap.put(Blocks.CACTUS, chunkSectionLayer2);
		hashMap.put(Blocks.SUGAR_CANE, chunkSectionLayer2);
		hashMap.put(Blocks.REPEATER, chunkSectionLayer2);
		hashMap.put(Blocks.OAK_TRAPDOOR, chunkSectionLayer2);
		hashMap.put(Blocks.SPRUCE_TRAPDOOR, chunkSectionLayer2);
		hashMap.put(Blocks.BIRCH_TRAPDOOR, chunkSectionLayer2);
		hashMap.put(Blocks.JUNGLE_TRAPDOOR, chunkSectionLayer2);
		hashMap.put(Blocks.ACACIA_TRAPDOOR, chunkSectionLayer2);
		hashMap.put(Blocks.CHERRY_TRAPDOOR, chunkSectionLayer2);
		hashMap.put(Blocks.DARK_OAK_TRAPDOOR, chunkSectionLayer2);
		hashMap.put(Blocks.PALE_OAK_TRAPDOOR, chunkSectionLayer2);
		hashMap.put(Blocks.CRIMSON_TRAPDOOR, chunkSectionLayer2);
		hashMap.put(Blocks.WARPED_TRAPDOOR, chunkSectionLayer2);
		hashMap.put(Blocks.MANGROVE_TRAPDOOR, chunkSectionLayer2);
		hashMap.put(Blocks.BAMBOO_TRAPDOOR, chunkSectionLayer2);
		hashMap.put(Blocks.COPPER_TRAPDOOR, chunkSectionLayer2);
		hashMap.put(Blocks.EXPOSED_COPPER_TRAPDOOR, chunkSectionLayer2);
		hashMap.put(Blocks.WEATHERED_COPPER_TRAPDOOR, chunkSectionLayer2);
		hashMap.put(Blocks.OXIDIZED_COPPER_TRAPDOOR, chunkSectionLayer2);
		hashMap.put(Blocks.WAXED_COPPER_TRAPDOOR, chunkSectionLayer2);
		hashMap.put(Blocks.WAXED_EXPOSED_COPPER_TRAPDOOR, chunkSectionLayer2);
		hashMap.put(Blocks.WAXED_WEATHERED_COPPER_TRAPDOOR, chunkSectionLayer2);
		hashMap.put(Blocks.WAXED_OXIDIZED_COPPER_TRAPDOOR, chunkSectionLayer2);
		hashMap.put(Blocks.ATTACHED_PUMPKIN_STEM, chunkSectionLayer2);
		hashMap.put(Blocks.ATTACHED_MELON_STEM, chunkSectionLayer2);
		hashMap.put(Blocks.PUMPKIN_STEM, chunkSectionLayer2);
		hashMap.put(Blocks.MELON_STEM, chunkSectionLayer2);
		hashMap.put(Blocks.VINE, chunkSectionLayer2);
		hashMap.put(Blocks.PALE_MOSS_CARPET, chunkSectionLayer2);
		hashMap.put(Blocks.PALE_HANGING_MOSS, chunkSectionLayer2);
		hashMap.put(Blocks.GLOW_LICHEN, chunkSectionLayer2);
		hashMap.put(Blocks.RESIN_CLUMP, chunkSectionLayer2);
		hashMap.put(Blocks.LILY_PAD, chunkSectionLayer2);
		hashMap.put(Blocks.NETHER_WART, chunkSectionLayer2);
		hashMap.put(Blocks.BREWING_STAND, chunkSectionLayer2);
		hashMap.put(Blocks.COCOA, chunkSectionLayer2);
		hashMap.put(Blocks.FLOWER_POT, chunkSectionLayer2);
		hashMap.put(Blocks.POTTED_OAK_SAPLING, chunkSectionLayer2);
		hashMap.put(Blocks.POTTED_SPRUCE_SAPLING, chunkSectionLayer2);
		hashMap.put(Blocks.POTTED_BIRCH_SAPLING, chunkSectionLayer2);
		hashMap.put(Blocks.POTTED_JUNGLE_SAPLING, chunkSectionLayer2);
		hashMap.put(Blocks.POTTED_ACACIA_SAPLING, chunkSectionLayer2);
		hashMap.put(Blocks.POTTED_CHERRY_SAPLING, chunkSectionLayer2);
		hashMap.put(Blocks.POTTED_DARK_OAK_SAPLING, chunkSectionLayer2);
		hashMap.put(Blocks.POTTED_PALE_OAK_SAPLING, chunkSectionLayer2);
		hashMap.put(Blocks.POTTED_MANGROVE_PROPAGULE, chunkSectionLayer2);
		hashMap.put(Blocks.POTTED_FERN, chunkSectionLayer2);
		hashMap.put(Blocks.POTTED_DANDELION, chunkSectionLayer2);
		hashMap.put(Blocks.POTTED_POPPY, chunkSectionLayer2);
		hashMap.put(Blocks.POTTED_OPEN_EYEBLOSSOM, chunkSectionLayer2);
		hashMap.put(Blocks.POTTED_CLOSED_EYEBLOSSOM, chunkSectionLayer2);
		hashMap.put(Blocks.POTTED_BLUE_ORCHID, chunkSectionLayer2);
		hashMap.put(Blocks.POTTED_ALLIUM, chunkSectionLayer2);
		hashMap.put(Blocks.POTTED_AZURE_BLUET, chunkSectionLayer2);
		hashMap.put(Blocks.POTTED_RED_TULIP, chunkSectionLayer2);
		hashMap.put(Blocks.POTTED_ORANGE_TULIP, chunkSectionLayer2);
		hashMap.put(Blocks.POTTED_WHITE_TULIP, chunkSectionLayer2);
		hashMap.put(Blocks.POTTED_PINK_TULIP, chunkSectionLayer2);
		hashMap.put(Blocks.POTTED_OXEYE_DAISY, chunkSectionLayer2);
		hashMap.put(Blocks.POTTED_CORNFLOWER, chunkSectionLayer2);
		hashMap.put(Blocks.POTTED_LILY_OF_THE_VALLEY, chunkSectionLayer2);
		hashMap.put(Blocks.POTTED_WITHER_ROSE, chunkSectionLayer2);
		hashMap.put(Blocks.POTTED_RED_MUSHROOM, chunkSectionLayer2);
		hashMap.put(Blocks.POTTED_BROWN_MUSHROOM, chunkSectionLayer2);
		hashMap.put(Blocks.POTTED_DEAD_BUSH, chunkSectionLayer2);
		hashMap.put(Blocks.POTTED_CACTUS, chunkSectionLayer2);
		hashMap.put(Blocks.POTTED_AZALEA, chunkSectionLayer2);
		hashMap.put(Blocks.POTTED_FLOWERING_AZALEA, chunkSectionLayer2);
		hashMap.put(Blocks.POTTED_TORCHFLOWER, chunkSectionLayer2);
		hashMap.put(Blocks.CARROTS, chunkSectionLayer2);
		hashMap.put(Blocks.POTATOES, chunkSectionLayer2);
		hashMap.put(Blocks.COMPARATOR, chunkSectionLayer2);
		hashMap.put(Blocks.ACTIVATOR_RAIL, chunkSectionLayer2);
		hashMap.put(Blocks.IRON_TRAPDOOR, chunkSectionLayer2);
		hashMap.put(Blocks.SUNFLOWER, chunkSectionLayer2);
		hashMap.put(Blocks.LILAC, chunkSectionLayer2);
		hashMap.put(Blocks.ROSE_BUSH, chunkSectionLayer2);
		hashMap.put(Blocks.PEONY, chunkSectionLayer2);
		hashMap.put(Blocks.TALL_GRASS, chunkSectionLayer2);
		hashMap.put(Blocks.LARGE_FERN, chunkSectionLayer2);
		hashMap.put(Blocks.SPRUCE_DOOR, chunkSectionLayer2);
		hashMap.put(Blocks.BIRCH_DOOR, chunkSectionLayer2);
		hashMap.put(Blocks.JUNGLE_DOOR, chunkSectionLayer2);
		hashMap.put(Blocks.ACACIA_DOOR, chunkSectionLayer2);
		hashMap.put(Blocks.CHERRY_DOOR, chunkSectionLayer2);
		hashMap.put(Blocks.DARK_OAK_DOOR, chunkSectionLayer2);
		hashMap.put(Blocks.PALE_OAK_DOOR, chunkSectionLayer2);
		hashMap.put(Blocks.MANGROVE_DOOR, chunkSectionLayer2);
		hashMap.put(Blocks.BAMBOO_DOOR, chunkSectionLayer2);
		hashMap.put(Blocks.COPPER_DOOR, chunkSectionLayer2);
		hashMap.put(Blocks.EXPOSED_COPPER_DOOR, chunkSectionLayer2);
		hashMap.put(Blocks.WEATHERED_COPPER_DOOR, chunkSectionLayer2);
		hashMap.put(Blocks.OXIDIZED_COPPER_DOOR, chunkSectionLayer2);
		hashMap.put(Blocks.WAXED_COPPER_DOOR, chunkSectionLayer2);
		hashMap.put(Blocks.WAXED_EXPOSED_COPPER_DOOR, chunkSectionLayer2);
		hashMap.put(Blocks.WAXED_WEATHERED_COPPER_DOOR, chunkSectionLayer2);
		hashMap.put(Blocks.WAXED_OXIDIZED_COPPER_DOOR, chunkSectionLayer2);
		hashMap.put(Blocks.END_ROD, chunkSectionLayer2);
		hashMap.put(Blocks.CHORUS_PLANT, chunkSectionLayer2);
		hashMap.put(Blocks.CHORUS_FLOWER, chunkSectionLayer2);
		hashMap.put(Blocks.TORCHFLOWER, chunkSectionLayer2);
		hashMap.put(Blocks.TORCHFLOWER_CROP, chunkSectionLayer2);
		hashMap.put(Blocks.PITCHER_PLANT, chunkSectionLayer2);
		hashMap.put(Blocks.PITCHER_CROP, chunkSectionLayer2);
		hashMap.put(Blocks.BEETROOTS, chunkSectionLayer2);
		hashMap.put(Blocks.KELP, chunkSectionLayer2);
		hashMap.put(Blocks.KELP_PLANT, chunkSectionLayer2);
		hashMap.put(Blocks.TURTLE_EGG, chunkSectionLayer2);
		hashMap.put(Blocks.DEAD_TUBE_CORAL, chunkSectionLayer2);
		hashMap.put(Blocks.DEAD_BRAIN_CORAL, chunkSectionLayer2);
		hashMap.put(Blocks.DEAD_BUBBLE_CORAL, chunkSectionLayer2);
		hashMap.put(Blocks.DEAD_FIRE_CORAL, chunkSectionLayer2);
		hashMap.put(Blocks.DEAD_HORN_CORAL, chunkSectionLayer2);
		hashMap.put(Blocks.TUBE_CORAL, chunkSectionLayer2);
		hashMap.put(Blocks.BRAIN_CORAL, chunkSectionLayer2);
		hashMap.put(Blocks.BUBBLE_CORAL, chunkSectionLayer2);
		hashMap.put(Blocks.FIRE_CORAL, chunkSectionLayer2);
		hashMap.put(Blocks.HORN_CORAL, chunkSectionLayer2);
		hashMap.put(Blocks.DEAD_TUBE_CORAL_FAN, chunkSectionLayer2);
		hashMap.put(Blocks.DEAD_BRAIN_CORAL_FAN, chunkSectionLayer2);
		hashMap.put(Blocks.DEAD_BUBBLE_CORAL_FAN, chunkSectionLayer2);
		hashMap.put(Blocks.DEAD_FIRE_CORAL_FAN, chunkSectionLayer2);
		hashMap.put(Blocks.DEAD_HORN_CORAL_FAN, chunkSectionLayer2);
		hashMap.put(Blocks.TUBE_CORAL_FAN, chunkSectionLayer2);
		hashMap.put(Blocks.BRAIN_CORAL_FAN, chunkSectionLayer2);
		hashMap.put(Blocks.BUBBLE_CORAL_FAN, chunkSectionLayer2);
		hashMap.put(Blocks.FIRE_CORAL_FAN, chunkSectionLayer2);
		hashMap.put(Blocks.HORN_CORAL_FAN, chunkSectionLayer2);
		hashMap.put(Blocks.DEAD_TUBE_CORAL_WALL_FAN, chunkSectionLayer2);
		hashMap.put(Blocks.DEAD_BRAIN_CORAL_WALL_FAN, chunkSectionLayer2);
		hashMap.put(Blocks.DEAD_BUBBLE_CORAL_WALL_FAN, chunkSectionLayer2);
		hashMap.put(Blocks.DEAD_FIRE_CORAL_WALL_FAN, chunkSectionLayer2);
		hashMap.put(Blocks.DEAD_HORN_CORAL_WALL_FAN, chunkSectionLayer2);
		hashMap.put(Blocks.TUBE_CORAL_WALL_FAN, chunkSectionLayer2);
		hashMap.put(Blocks.BRAIN_CORAL_WALL_FAN, chunkSectionLayer2);
		hashMap.put(Blocks.BUBBLE_CORAL_WALL_FAN, chunkSectionLayer2);
		hashMap.put(Blocks.FIRE_CORAL_WALL_FAN, chunkSectionLayer2);
		hashMap.put(Blocks.HORN_CORAL_WALL_FAN, chunkSectionLayer2);
		hashMap.put(Blocks.SEA_PICKLE, chunkSectionLayer2);
		hashMap.put(Blocks.CONDUIT, chunkSectionLayer2);
		hashMap.put(Blocks.BAMBOO_SAPLING, chunkSectionLayer2);
		hashMap.put(Blocks.BAMBOO, chunkSectionLayer2);
		hashMap.put(Blocks.POTTED_BAMBOO, chunkSectionLayer2);
		hashMap.put(Blocks.SCAFFOLDING, chunkSectionLayer2);
		hashMap.put(Blocks.STONECUTTER, chunkSectionLayer2);
		hashMap.put(Blocks.LANTERN, chunkSectionLayer2);
		hashMap.put(Blocks.SOUL_LANTERN, chunkSectionLayer2);
		Blocks.COPPER_LANTERN.forEach(block -> hashMap.put(block, chunkSectionLayer2));
		hashMap.put(Blocks.CAMPFIRE, chunkSectionLayer2);
		hashMap.put(Blocks.SOUL_CAMPFIRE, chunkSectionLayer2);
		hashMap.put(Blocks.SWEET_BERRY_BUSH, chunkSectionLayer2);
		hashMap.put(Blocks.WEEPING_VINES, chunkSectionLayer2);
		hashMap.put(Blocks.WEEPING_VINES_PLANT, chunkSectionLayer2);
		hashMap.put(Blocks.TWISTING_VINES, chunkSectionLayer2);
		hashMap.put(Blocks.TWISTING_VINES_PLANT, chunkSectionLayer2);
		hashMap.put(Blocks.NETHER_SPROUTS, chunkSectionLayer2);
		hashMap.put(Blocks.CRIMSON_FUNGUS, chunkSectionLayer2);
		hashMap.put(Blocks.WARPED_FUNGUS, chunkSectionLayer2);
		hashMap.put(Blocks.CRIMSON_ROOTS, chunkSectionLayer2);
		hashMap.put(Blocks.WARPED_ROOTS, chunkSectionLayer2);
		hashMap.put(Blocks.POTTED_CRIMSON_FUNGUS, chunkSectionLayer2);
		hashMap.put(Blocks.POTTED_WARPED_FUNGUS, chunkSectionLayer2);
		hashMap.put(Blocks.POTTED_CRIMSON_ROOTS, chunkSectionLayer2);
		hashMap.put(Blocks.POTTED_WARPED_ROOTS, chunkSectionLayer2);
		hashMap.put(Blocks.CRIMSON_DOOR, chunkSectionLayer2);
		hashMap.put(Blocks.WARPED_DOOR, chunkSectionLayer2);
		hashMap.put(Blocks.POINTED_DRIPSTONE, chunkSectionLayer2);
		hashMap.put(Blocks.SMALL_AMETHYST_BUD, chunkSectionLayer2);
		hashMap.put(Blocks.MEDIUM_AMETHYST_BUD, chunkSectionLayer2);
		hashMap.put(Blocks.LARGE_AMETHYST_BUD, chunkSectionLayer2);
		hashMap.put(Blocks.AMETHYST_CLUSTER, chunkSectionLayer2);
		hashMap.put(Blocks.CAVE_VINES, chunkSectionLayer2);
		hashMap.put(Blocks.CAVE_VINES_PLANT, chunkSectionLayer2);
		hashMap.put(Blocks.SPORE_BLOSSOM, chunkSectionLayer2);
		hashMap.put(Blocks.FLOWERING_AZALEA, chunkSectionLayer2);
		hashMap.put(Blocks.AZALEA, chunkSectionLayer2);
		hashMap.put(Blocks.PINK_PETALS, chunkSectionLayer2);
		hashMap.put(Blocks.WILDFLOWERS, chunkSectionLayer2);
		hashMap.put(Blocks.LEAF_LITTER, chunkSectionLayer2);
		hashMap.put(Blocks.BIG_DRIPLEAF, chunkSectionLayer2);
		hashMap.put(Blocks.BIG_DRIPLEAF_STEM, chunkSectionLayer2);
		hashMap.put(Blocks.SMALL_DRIPLEAF, chunkSectionLayer2);
		hashMap.put(Blocks.HANGING_ROOTS, chunkSectionLayer2);
		hashMap.put(Blocks.SCULK_SENSOR, chunkSectionLayer2);
		hashMap.put(Blocks.CALIBRATED_SCULK_SENSOR, chunkSectionLayer2);
		hashMap.put(Blocks.SCULK_VEIN, chunkSectionLayer2);
		hashMap.put(Blocks.SCULK_SHRIEKER, chunkSectionLayer2);
		hashMap.put(Blocks.MANGROVE_PROPAGULE, chunkSectionLayer2);
		hashMap.put(Blocks.FROGSPAWN, chunkSectionLayer2);
		hashMap.put(Blocks.COPPER_GRATE, chunkSectionLayer2);
		hashMap.put(Blocks.EXPOSED_COPPER_GRATE, chunkSectionLayer2);
		hashMap.put(Blocks.WEATHERED_COPPER_GRATE, chunkSectionLayer2);
		hashMap.put(Blocks.OXIDIZED_COPPER_GRATE, chunkSectionLayer2);
		hashMap.put(Blocks.WAXED_COPPER_GRATE, chunkSectionLayer2);
		hashMap.put(Blocks.WAXED_EXPOSED_COPPER_GRATE, chunkSectionLayer2);
		hashMap.put(Blocks.WAXED_WEATHERED_COPPER_GRATE, chunkSectionLayer2);
		hashMap.put(Blocks.WAXED_OXIDIZED_COPPER_GRATE, chunkSectionLayer2);
		hashMap.put(Blocks.FIREFLY_BUSH, chunkSectionLayer2);
		hashMap.put(Blocks.CACTUS_FLOWER, chunkSectionLayer2);
		hashMap.put(Blocks.BEACON, chunkSectionLayer2);
		ChunkSectionLayer chunkSectionLayer3 = ChunkSectionLayer.TRANSLUCENT;
		hashMap.put(Blocks.ICE, chunkSectionLayer3);
		hashMap.put(Blocks.NETHER_PORTAL, chunkSectionLayer3);
		hashMap.put(Blocks.GLASS, chunkSectionLayer3);
		hashMap.put(Blocks.GLASS_PANE, chunkSectionLayer3);
		hashMap.put(Blocks.WHITE_STAINED_GLASS, chunkSectionLayer3);
		hashMap.put(Blocks.ORANGE_STAINED_GLASS, chunkSectionLayer3);
		hashMap.put(Blocks.MAGENTA_STAINED_GLASS, chunkSectionLayer3);
		hashMap.put(Blocks.LIGHT_BLUE_STAINED_GLASS, chunkSectionLayer3);
		hashMap.put(Blocks.YELLOW_STAINED_GLASS, chunkSectionLayer3);
		hashMap.put(Blocks.LIME_STAINED_GLASS, chunkSectionLayer3);
		hashMap.put(Blocks.PINK_STAINED_GLASS, chunkSectionLayer3);
		hashMap.put(Blocks.GRAY_STAINED_GLASS, chunkSectionLayer3);
		hashMap.put(Blocks.LIGHT_GRAY_STAINED_GLASS, chunkSectionLayer3);
		hashMap.put(Blocks.CYAN_STAINED_GLASS, chunkSectionLayer3);
		hashMap.put(Blocks.PURPLE_STAINED_GLASS, chunkSectionLayer3);
		hashMap.put(Blocks.BLUE_STAINED_GLASS, chunkSectionLayer3);
		hashMap.put(Blocks.BROWN_STAINED_GLASS, chunkSectionLayer3);
		hashMap.put(Blocks.GREEN_STAINED_GLASS, chunkSectionLayer3);
		hashMap.put(Blocks.REDSTONE_WIRE, chunkSectionLayer3);
		hashMap.put(Blocks.RED_STAINED_GLASS, chunkSectionLayer3);
		hashMap.put(Blocks.BLACK_STAINED_GLASS, chunkSectionLayer3);
		hashMap.put(Blocks.WHITE_STAINED_GLASS_PANE, chunkSectionLayer3);
		hashMap.put(Blocks.ORANGE_STAINED_GLASS_PANE, chunkSectionLayer3);
		hashMap.put(Blocks.MAGENTA_STAINED_GLASS_PANE, chunkSectionLayer3);
		hashMap.put(Blocks.LIGHT_BLUE_STAINED_GLASS_PANE, chunkSectionLayer3);
		hashMap.put(Blocks.YELLOW_STAINED_GLASS_PANE, chunkSectionLayer3);
		hashMap.put(Blocks.LIME_STAINED_GLASS_PANE, chunkSectionLayer3);
		hashMap.put(Blocks.PINK_STAINED_GLASS_PANE, chunkSectionLayer3);
		hashMap.put(Blocks.GRAY_STAINED_GLASS_PANE, chunkSectionLayer3);
		hashMap.put(Blocks.LIGHT_GRAY_STAINED_GLASS_PANE, chunkSectionLayer3);
		hashMap.put(Blocks.CYAN_STAINED_GLASS_PANE, chunkSectionLayer3);
		hashMap.put(Blocks.PURPLE_STAINED_GLASS_PANE, chunkSectionLayer3);
		hashMap.put(Blocks.BLUE_STAINED_GLASS_PANE, chunkSectionLayer3);
		hashMap.put(Blocks.BROWN_STAINED_GLASS_PANE, chunkSectionLayer3);
		hashMap.put(Blocks.GREEN_STAINED_GLASS_PANE, chunkSectionLayer3);
		hashMap.put(Blocks.RED_STAINED_GLASS_PANE, chunkSectionLayer3);
		hashMap.put(Blocks.BLACK_STAINED_GLASS_PANE, chunkSectionLayer3);
		hashMap.put(Blocks.SLIME_BLOCK, chunkSectionLayer3);
		hashMap.put(Blocks.HONEY_BLOCK, chunkSectionLayer3);
		hashMap.put(Blocks.FROSTED_ICE, chunkSectionLayer3);
		hashMap.put(Blocks.BUBBLE_COLUMN, chunkSectionLayer3);
		hashMap.put(Blocks.TINTED_GLASS, chunkSectionLayer3);
	});
	private static final Map<Fluid, ChunkSectionLayer> LAYER_BY_FLUID = Util.make(Maps.newHashMap(), hashMap -> {
		hashMap.put(Fluids.FLOWING_WATER, ChunkSectionLayer.TRANSLUCENT);
		hashMap.put(Fluids.WATER, ChunkSectionLayer.TRANSLUCENT);
	});
	private static boolean cutoutLeaves;

	public static ChunkSectionLayer getChunkRenderType(BlockState blockState) {
		Block block = blockState.getBlock();
		if (block instanceof LeavesBlock) {
			return cutoutLeaves ? ChunkSectionLayer.CUTOUT : ChunkSectionLayer.SOLID;
		}

		ChunkSectionLayer chunkSectionLayer = TYPE_BY_BLOCK.get(block);
		return chunkSectionLayer != null ? chunkSectionLayer : ChunkSectionLayer.SOLID;
	}

	public static RenderType getMovingBlockRenderType(BlockState blockState) {
		Block block = blockState.getBlock();
		if (block instanceof LeavesBlock) {
			return cutoutLeaves ? RenderTypes.cutoutMovingBlock() : RenderTypes.solidMovingBlock();
		}

		ChunkSectionLayer chunkSectionLayer = TYPE_BY_BLOCK.get(block);
		if (chunkSectionLayer != null) {
			return switch (chunkSectionLayer) {
				case SOLID -> RenderTypes.solidMovingBlock();
				case CUTOUT -> RenderTypes.cutoutMovingBlock();
				case TRANSLUCENT -> RenderTypes.translucentMovingBlock();
				case TRIPWIRE -> RenderTypes.tripwireMovingBlock();
			};
		} else {
			return RenderTypes.solidMovingBlock();
		}
	}

	public static RenderType getRenderType(BlockState blockState) {
		ChunkSectionLayer chunkSectionLayer = getChunkRenderType(blockState);
		return chunkSectionLayer == ChunkSectionLayer.TRANSLUCENT ? Sheets.translucentBlockItemSheet() : Sheets.cutoutBlockSheet();
	}

	public static ChunkSectionLayer getRenderLayer(FluidState fluidState) {
		ChunkSectionLayer chunkSectionLayer = LAYER_BY_FLUID.get(fluidState.getType());
		return chunkSectionLayer != null ? chunkSectionLayer : ChunkSectionLayer.SOLID;
	}

	public static void setCutoutLeaves(boolean bl) {
		cutoutLeaves = bl;
	}
}
