package net.minecraft.client.model.geom;

import com.google.common.collect.ImmutableMap;
import com.google.common.collect.ImmutableMap.Builder;
import java.util.List;
import java.util.Map;
import net.fabricmc.api.EnvType;
import net.fabricmc.api.Environment;
import net.minecraft.client.model.HumanoidModel;
import net.minecraft.client.model.ambient.BatModel;
import net.minecraft.client.model.animal.allay.AllayModel;
import net.minecraft.client.model.animal.armadillo.ArmadilloModel;
import net.minecraft.client.model.animal.axolotl.AxolotlModel;
import net.minecraft.client.model.animal.bee.BeeModel;
import net.minecraft.client.model.animal.bee.BeeStingerModel;
import net.minecraft.client.model.animal.camel.CamelModel;
import net.minecraft.client.model.animal.camel.CamelSaddleModel;
import net.minecraft.client.model.animal.chicken.ChickenModel;
import net.minecraft.client.model.animal.chicken.ColdChickenModel;
import net.minecraft.client.model.animal.cow.ColdCowModel;
import net.minecraft.client.model.animal.cow.CowModel;
import net.minecraft.client.model.animal.cow.WarmCowModel;
import net.minecraft.client.model.animal.dolphin.DolphinModel;
import net.minecraft.client.model.animal.equine.AbstractEquineModel;
import net.minecraft.client.model.animal.equine.DonkeyModel;
import net.minecraft.client.model.animal.equine.EquineSaddleModel;
import net.minecraft.client.model.animal.feline.CatModel;
import net.minecraft.client.model.animal.feline.FelineModel;
import net.minecraft.client.model.animal.fish.CodModel;
import net.minecraft.client.model.animal.fish.PufferfishBigModel;
import net.minecraft.client.model.animal.fish.PufferfishMidModel;
import net.minecraft.client.model.animal.fish.PufferfishSmallModel;
import net.minecraft.client.model.animal.fish.SalmonModel;
import net.minecraft.client.model.animal.fish.TropicalFishLargeModel;
import net.minecraft.client.model.animal.fish.TropicalFishSmallModel;
import net.minecraft.client.model.animal.fox.FoxModel;
import net.minecraft.client.model.animal.frog.FrogModel;
import net.minecraft.client.model.animal.frog.TadpoleModel;
import net.minecraft.client.model.animal.ghast.HappyGhastHarnessModel;
import net.minecraft.client.model.animal.ghast.HappyGhastModel;
import net.minecraft.client.model.animal.goat.GoatModel;
import net.minecraft.client.model.animal.golem.CopperGolemModel;
import net.minecraft.client.model.animal.golem.IronGolemModel;
import net.minecraft.client.model.animal.golem.SnowGolemModel;
import net.minecraft.client.model.animal.llama.LlamaModel;
import net.minecraft.client.model.animal.llama.LlamaSpitModel;
import net.minecraft.client.model.animal.nautilus.NautilusArmorModel;
import net.minecraft.client.model.animal.nautilus.NautilusModel;
import net.minecraft.client.model.animal.nautilus.NautilusSaddleModel;
import net.minecraft.client.model.animal.panda.PandaModel;
import net.minecraft.client.model.animal.parrot.ParrotModel;
import net.minecraft.client.model.animal.pig.ColdPigModel;
import net.minecraft.client.model.animal.pig.PigModel;
import net.minecraft.client.model.animal.polarbear.PolarBearModel;
import net.minecraft.client.model.animal.rabbit.RabbitModel;
import net.minecraft.client.model.animal.sheep.SheepFurModel;
import net.minecraft.client.model.animal.sheep.SheepModel;
import net.minecraft.client.model.animal.sniffer.SnifferModel;
import net.minecraft.client.model.animal.squid.SquidModel;
import net.minecraft.client.model.animal.turtle.TurtleModel;
import net.minecraft.client.model.animal.wolf.WolfModel;
import net.minecraft.client.model.effects.EvokerFangsModel;
import net.minecraft.client.model.effects.SpinAttackEffectModel;
import net.minecraft.client.model.geom.builders.CubeDeformation;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshTransformer;
import net.minecraft.client.model.monster.blaze.BlazeModel;
import net.minecraft.client.model.monster.breeze.BreezeModel;
import net.minecraft.client.model.monster.creaking.CreakingModel;
import net.minecraft.client.model.monster.creeper.CreeperModel;
import net.minecraft.client.model.monster.dragon.EnderDragonModel;
import net.minecraft.client.model.monster.enderman.EndermanModel;
import net.minecraft.client.model.monster.endermite.EndermiteModel;
import net.minecraft.client.model.monster.ghast.GhastModel;
import net.minecraft.client.model.monster.guardian.GuardianModel;
import net.minecraft.client.model.monster.hoglin.HoglinModel;
import net.minecraft.client.model.monster.illager.IllagerModel;
import net.minecraft.client.model.monster.nautilus.ZombieNautilusCoralModel;
import net.minecraft.client.model.monster.phantom.PhantomModel;
import net.minecraft.client.model.monster.piglin.PiglinModel;
import net.minecraft.client.model.monster.ravager.RavagerModel;
import net.minecraft.client.model.monster.shulker.ShulkerModel;
import net.minecraft.client.model.monster.silverfish.SilverfishModel;
import net.minecraft.client.model.monster.skeleton.BoggedModel;
import net.minecraft.client.model.monster.skeleton.SkeletonModel;
import net.minecraft.client.model.monster.slime.MagmaCubeModel;
import net.minecraft.client.model.monster.slime.SlimeModel;
import net.minecraft.client.model.monster.spider.SpiderModel;
import net.minecraft.client.model.monster.strider.StriderModel;
import net.minecraft.client.model.monster.vex.VexModel;
import net.minecraft.client.model.monster.warden.WardenModel;
import net.minecraft.client.model.monster.witch.WitchModel;
import net.minecraft.client.model.monster.wither.WitherBossModel;
import net.minecraft.client.model.monster.zombie.DrownedModel;
import net.minecraft.client.model.monster.zombie.ZombieVillagerModel;
import net.minecraft.client.model.npc.VillagerModel;
import net.minecraft.client.model.object.armorstand.ArmorStandArmorModel;
import net.minecraft.client.model.object.armorstand.ArmorStandModel;
import net.minecraft.client.model.object.banner.BannerFlagModel;
import net.minecraft.client.model.object.banner.BannerModel;
import net.minecraft.client.model.object.bell.BellModel;
import net.minecraft.client.model.object.boat.BoatModel;
import net.minecraft.client.model.object.boat.RaftModel;
import net.minecraft.client.model.object.book.BookModel;
import net.minecraft.client.model.object.cart.MinecartModel;
import net.minecraft.client.model.object.chest.ChestModel;
import net.minecraft.client.model.object.crystal.EndCrystalModel;
import net.minecraft.client.model.object.equipment.ElytraModel;
import net.minecraft.client.model.object.equipment.ShieldModel;
import net.minecraft.client.model.object.leash.LeashKnotModel;
import net.minecraft.client.model.object.projectile.ArrowModel;
import net.minecraft.client.model.object.projectile.ShulkerBulletModel;
import net.minecraft.client.model.object.projectile.TridentModel;
import net.minecraft.client.model.object.projectile.WindChargeModel;
import net.minecraft.client.model.object.skull.DragonHeadModel;
import net.minecraft.client.model.object.skull.PiglinHeadModel;
import net.minecraft.client.model.object.skull.SkullModel;
import net.minecraft.client.model.player.PlayerCapeModel;
import net.minecraft.client.model.player.PlayerEarsModel;
import net.minecraft.client.model.player.PlayerModel;
import net.minecraft.client.renderer.blockentity.BedRenderer;
import net.minecraft.client.renderer.blockentity.ConduitRenderer;
import net.minecraft.client.renderer.blockentity.DecoratedPotRenderer;
import net.minecraft.client.renderer.blockentity.HangingSignRenderer;
import net.minecraft.client.renderer.blockentity.SignRenderer;
import net.minecraft.client.renderer.entity.ArmorModelSet;
import net.minecraft.client.renderer.entity.WitherSkullRenderer;
import net.minecraft.world.level.block.state.properties.WoodType;

@Environment(EnvType.CLIENT)
public class LayerDefinitions {
	private static final CubeDeformation FISH_PATTERN_DEFORMATION = new CubeDeformation(0.008F);
	private static final CubeDeformation OUTER_ARMOR_DEFORMATION = new CubeDeformation(1.0F);
	private static final CubeDeformation INNER_ARMOR_DEFORMATION = new CubeDeformation(0.5F);

	public static Map<ModelLayerLocation, LayerDefinition> createRoots() {
		Builder<ModelLayerLocation, LayerDefinition> builder = ImmutableMap.builder();
		LayerDefinition layerDefinition = LayerDefinition.create(HumanoidModel.createMesh(CubeDeformation.NONE, 0.0F), 64, 64);
		ArmorModelSet<LayerDefinition> armorModelSet = HumanoidModel.createArmorMeshSet(INNER_ARMOR_DEFORMATION, OUTER_ARMOR_DEFORMATION)
			.map(meshDefinition -> LayerDefinition.create(meshDefinition, 64, 32));
		ArmorModelSet<LayerDefinition> armorModelSet2 = armorModelSet.map(layerDefinitionx -> layerDefinitionx.apply(HumanoidModel.BABY_TRANSFORMER));
		ArmorModelSet<LayerDefinition> armorModelSet3 = PlayerModel.createArmorMeshSet(INNER_ARMOR_DEFORMATION, OUTER_ARMOR_DEFORMATION)
			.map(meshDefinition -> LayerDefinition.create(meshDefinition, 64, 32));
		ArmorModelSet<LayerDefinition> armorModelSet4 = PiglinModel.createArmorMeshSet(INNER_ARMOR_DEFORMATION, new CubeDeformation(1.02F))
			.map(meshDefinition -> LayerDefinition.create(meshDefinition, 64, 32));
		ArmorModelSet<LayerDefinition> armorModelSet5 = armorModelSet4.map(layerDefinitionx -> layerDefinitionx.apply(HumanoidModel.BABY_TRANSFORMER));
		LayerDefinition layerDefinition2 = MinecartModel.createBodyLayer();
		LayerDefinition layerDefinition3 = SkullModel.createMobHeadLayer();
		LayerDefinition layerDefinition4 = LayerDefinition.create(AbstractEquineModel.createBodyMesh(CubeDeformation.NONE), 64, 64);
		LayerDefinition layerDefinition5 = LayerDefinition.create(AbstractEquineModel.createBabyMesh(CubeDeformation.NONE), 64, 64);
		LayerDefinition layerDefinition6 = EquineSaddleModel.createSaddleLayer(false);
		LayerDefinition layerDefinition7 = EquineSaddleModel.createSaddleLayer(true);
		MeshTransformer meshTransformer = MeshTransformer.scaling(0.9375F);
		LayerDefinition layerDefinition8 = IllagerModel.createBodyLayer().apply(meshTransformer);
		LayerDefinition layerDefinition9 = AxolotlModel.createBodyLayer();
		LayerDefinition layerDefinition10 = BeeModel.createBodyLayer();
		LayerDefinition layerDefinition11 = CowModel.createBodyLayer();
		LayerDefinition layerDefinition12 = ColdChickenModel.createBodyLayer();
		LayerDefinition layerDefinition13 = ColdCowModel.createBodyLayer();
		LayerDefinition layerDefinition14 = ColdPigModel.createBodyLayer(CubeDeformation.NONE);
		LayerDefinition layerDefinition15 = ElytraModel.createLayer();
		LayerDefinition layerDefinition16 = LayerDefinition.create(FelineModel.createBodyMesh(CubeDeformation.NONE), 64, 32);
		LayerDefinition layerDefinition17 = layerDefinition16.apply(FelineModel.BABY_TRANSFORMER);
		LayerDefinition layerDefinition18 = LayerDefinition.create(FelineModel.createBodyMesh(new CubeDeformation(0.01F)), 64, 32);
		LayerDefinition layerDefinition19 = LayerDefinition.create(PiglinModel.createMesh(CubeDeformation.NONE), 64, 64);
		LayerDefinition layerDefinition20 = LayerDefinition.create(PiglinHeadModel.createHeadModel(), 64, 64);
		LayerDefinition layerDefinition21 = SkullModel.createHumanoidHeadLayer();
		LayerDefinition layerDefinition22 = LlamaModel.createBodyLayer(CubeDeformation.NONE);
		LayerDefinition layerDefinition23 = LlamaModel.createBodyLayer(new CubeDeformation(0.5F));
		LayerDefinition layerDefinition24 = StriderModel.createBodyLayer();
		LayerDefinition layerDefinition25 = HoglinModel.createBodyLayer();
		LayerDefinition layerDefinition26 = HoglinModel.createBabyLayer();
		LayerDefinition layerDefinition27 = SkeletonModel.createBodyLayer();
		LayerDefinition layerDefinition28 = LayerDefinition.create(VillagerModel.createBodyModel(), 64, 64).apply(meshTransformer);
		LayerDefinition layerDefinition29 = LayerDefinition.create(VillagerModel.createNoHatModel(), 64, 64).apply(meshTransformer);
		LayerDefinition layerDefinition30 = SpiderModel.createSpiderBodyLayer();
		LayerDefinition layerDefinition31 = ArmadilloModel.createBodyLayer();
		LayerDefinition layerDefinition32 = CamelModel.createBodyLayer();
		LayerDefinition layerDefinition33 = CamelSaddleModel.createSaddleLayer();
		LayerDefinition layerDefinition34 = ChickenModel.createBodyLayer();
		LayerDefinition layerDefinition35 = GoatModel.createBodyLayer();
		LayerDefinition layerDefinition36 = PandaModel.createBodyLayer();
		LayerDefinition layerDefinition37 = PigModel.createBodyLayer(CubeDeformation.NONE);
		LayerDefinition layerDefinition38 = PigModel.createBodyLayer(new CubeDeformation(0.5F));
		LayerDefinition layerDefinition39 = SheepModel.createBodyLayer();
		LayerDefinition layerDefinition40 = SheepFurModel.createFurLayer();
		LayerDefinition layerDefinition41 = SnifferModel.createBodyLayer();
		LayerDefinition layerDefinition42 = TurtleModel.createBodyLayer();
		LayerDefinition layerDefinition43 = WarmCowModel.createBodyLayer();
		LayerDefinition layerDefinition44 = LayerDefinition.create(WolfModel.createMeshDefinition(CubeDeformation.NONE), 64, 32);
		LayerDefinition layerDefinition45 = LayerDefinition.create(WolfModel.createMeshDefinition(new CubeDeformation(0.2F)), 64, 32);
		LayerDefinition layerDefinition46 = ZombieVillagerModel.createBodyLayer();
		LayerDefinition layerDefinition47 = ZombieVillagerModel.createNoHatLayer();
		LayerDefinition layerDefinition48 = ArmorStandModel.createBodyLayer();
		ArmorModelSet<LayerDefinition> armorModelSet6 = ArmorStandArmorModel.createArmorLayerSet(INNER_ARMOR_DEFORMATION, OUTER_ARMOR_DEFORMATION);
		LayerDefinition layerDefinition49 = DrownedModel.createBodyLayer(CubeDeformation.NONE);
		LayerDefinition layerDefinition50 = DrownedModel.createBodyLayer(new CubeDeformation(0.25F));
		LayerDefinition layerDefinition51 = SquidModel.createBodyLayer();
		LayerDefinition layerDefinition52 = DolphinModel.createBodyLayer();
		LayerDefinition layerDefinition53 = SalmonModel.createBodyLayer();
		LayerDefinition layerDefinition54 = NautilusSaddleModel.createSaddleLayer();
		builder.put(ModelLayers.ALLAY, AllayModel.createBodyLayer());
		builder.put(ModelLayers.ARMADILLO, layerDefinition31);
		builder.put(ModelLayers.ARMADILLO_BABY, layerDefinition31.apply(ArmadilloModel.BABY_TRANSFORMER));
		builder.put(ModelLayers.ARMOR_STAND, layerDefinition48);
		ModelLayers.ARMOR_STAND_ARMOR.putFrom(armorModelSet6, builder);
		builder.put(ModelLayers.ARMOR_STAND_SMALL, layerDefinition48.apply(HumanoidModel.BABY_TRANSFORMER));
		ModelLayers.ARMOR_STAND_SMALL_ARMOR.putFrom(armorModelSet6.map(layerDefinitionx -> layerDefinitionx.apply(HumanoidModel.BABY_TRANSFORMER)), builder);
		builder.put(ModelLayers.ARROW, ArrowModel.createBodyLayer());
		builder.put(ModelLayers.AXOLOTL, layerDefinition9);
		builder.put(ModelLayers.AXOLOTL_BABY, layerDefinition9.apply(AxolotlModel.BABY_TRANSFORMER));
		builder.put(ModelLayers.STANDING_BANNER, BannerModel.createBodyLayer(true));
		builder.put(ModelLayers.WALL_BANNER, BannerModel.createBodyLayer(false));
		builder.put(ModelLayers.STANDING_BANNER_FLAG, BannerFlagModel.createFlagLayer(true));
		builder.put(ModelLayers.WALL_BANNER_FLAG, BannerFlagModel.createFlagLayer(false));
		builder.put(ModelLayers.BAT, BatModel.createBodyLayer());
		builder.put(ModelLayers.BED_FOOT, BedRenderer.createFootLayer());
		builder.put(ModelLayers.BED_HEAD, BedRenderer.createHeadLayer());
		builder.put(ModelLayers.BEE, layerDefinition10);
		builder.put(ModelLayers.BEE_BABY, layerDefinition10.apply(BeeModel.BABY_TRANSFORMER));
		builder.put(ModelLayers.BEE_STINGER, BeeStingerModel.createBodyLayer());
		builder.put(ModelLayers.BELL, BellModel.createBodyLayer());
		builder.put(ModelLayers.BLAZE, BlazeModel.createBodyLayer());
		builder.put(ModelLayers.BOAT_WATER_PATCH, BoatModel.createWaterPatch());
		builder.put(ModelLayers.BOGGED, BoggedModel.createBodyLayer());
		ModelLayers.BOGGED_ARMOR.putFrom(armorModelSet, builder);
		builder.put(ModelLayers.BOGGED_OUTER_LAYER, LayerDefinition.create(HumanoidModel.createMesh(new CubeDeformation(0.2F), 0.0F), 64, 32));
		builder.put(ModelLayers.BOOK, BookModel.createBodyLayer());
		builder.put(ModelLayers.BREEZE, BreezeModel.createBodyLayer());
		builder.put(ModelLayers.BREEZE_WIND, BreezeModel.createWindLayer());
		builder.put(ModelLayers.BREEZE_EYES, BreezeModel.createEyesLayer());
		builder.put(ModelLayers.CAT, layerDefinition16.apply(CatModel.CAT_TRANSFORMER));
		builder.put(ModelLayers.CAT_BABY, layerDefinition17.apply(CatModel.CAT_TRANSFORMER));
		builder.put(ModelLayers.CAT_COLLAR, layerDefinition18.apply(CatModel.CAT_TRANSFORMER));
		builder.put(ModelLayers.CAT_BABY_COLLAR, layerDefinition18.apply(FelineModel.BABY_TRANSFORMER).apply(CatModel.CAT_TRANSFORMER));
		builder.put(ModelLayers.CAMEL, layerDefinition32);
		builder.put(ModelLayers.CAMEL_BABY, layerDefinition32.apply(CamelModel.BABY_TRANSFORMER));
		builder.put(ModelLayers.CAMEL_SADDLE, layerDefinition33);
		builder.put(ModelLayers.CAMEL_BABY_SADDLE, layerDefinition33.apply(CamelModel.BABY_TRANSFORMER));
		builder.put(ModelLayers.CAMEL_HUSK_SADDLE, layerDefinition33);
		builder.put(ModelLayers.CAMEL_HUSK_BABY_SADDLE, layerDefinition33.apply(CamelModel.BABY_TRANSFORMER));
		builder.put(ModelLayers.CAVE_SPIDER, layerDefinition30.apply(MeshTransformer.scaling(0.7F)));
		builder.put(ModelLayers.CHEST, ChestModel.createSingleBodyLayer());
		builder.put(ModelLayers.CHEST_MINECART, layerDefinition2);
		builder.put(ModelLayers.CHICKEN, layerDefinition34);
		builder.put(ModelLayers.CHICKEN_BABY, layerDefinition34.apply(ChickenModel.BABY_TRANSFORMER));
		builder.put(ModelLayers.COD, CodModel.createBodyLayer());
		builder.put(ModelLayers.COLD_CHICKEN, layerDefinition12);
		builder.put(ModelLayers.COLD_CHICKEN_BABY, layerDefinition12.apply(ChickenModel.BABY_TRANSFORMER));
		builder.put(ModelLayers.COLD_COW, layerDefinition13);
		builder.put(ModelLayers.COLD_COW_BABY, layerDefinition13.apply(CowModel.BABY_TRANSFORMER));
		builder.put(ModelLayers.COLD_PIG, layerDefinition14);
		builder.put(ModelLayers.COLD_PIG_BABY, layerDefinition14.apply(PigModel.BABY_TRANSFORMER));
		builder.put(ModelLayers.COMMAND_BLOCK_MINECART, layerDefinition2);
		builder.put(ModelLayers.CONDUIT_EYE, ConduitRenderer.createEyeLayer());
		builder.put(ModelLayers.CONDUIT_WIND, ConduitRenderer.createWindLayer());
		builder.put(ModelLayers.CONDUIT_SHELL, ConduitRenderer.createShellLayer());
		builder.put(ModelLayers.CONDUIT_CAGE, ConduitRenderer.createCageLayer());
		builder.put(ModelLayers.COPPER_GOLEM, CopperGolemModel.createBodyLayer());
		builder.put(ModelLayers.COPPER_GOLEM_EYES, CopperGolemModel.createEyesLayer());
		builder.put(ModelLayers.COPPER_GOLEM_RUNNING, CopperGolemModel.createRunningPoseBodyLayer());
		builder.put(ModelLayers.COPPER_GOLEM_SITTING, CopperGolemModel.createSittingPoseBodyLayer());
		builder.put(ModelLayers.COPPER_GOLEM_STAR, CopperGolemModel.createStarPoseBodyLayer());
		builder.put(ModelLayers.COW, layerDefinition11);
		builder.put(ModelLayers.COW_BABY, layerDefinition11.apply(CowModel.BABY_TRANSFORMER));
		builder.put(ModelLayers.CREAKING, CreakingModel.createBodyLayer());
		builder.put(ModelLayers.CREAKING_EYES, CreakingModel.createEyesLayer());
		builder.put(ModelLayers.CREEPER, CreeperModel.createBodyLayer(CubeDeformation.NONE));
		builder.put(ModelLayers.CREEPER_ARMOR, CreeperModel.createBodyLayer(new CubeDeformation(2.0F)));
		builder.put(ModelLayers.CREEPER_HEAD, layerDefinition3);
		builder.put(ModelLayers.DECORATED_POT_BASE, DecoratedPotRenderer.createBaseLayer());
		builder.put(ModelLayers.DECORATED_POT_SIDES, DecoratedPotRenderer.createSidesLayer());
		builder.put(ModelLayers.DOLPHIN, layerDefinition52);
		builder.put(ModelLayers.DOLPHIN_BABY, layerDefinition52.apply(DolphinModel.BABY_TRANSFORMER));
		builder.put(ModelLayers.DONKEY, DonkeyModel.createBodyLayer(0.87F));
		builder.put(ModelLayers.DONKEY_BABY, DonkeyModel.createBabyLayer(0.87F));
		builder.put(ModelLayers.DONKEY_SADDLE, DonkeyModel.createSaddleLayer(0.87F, false));
		builder.put(ModelLayers.DONKEY_BABY_SADDLE, DonkeyModel.createSaddleLayer(0.87F, true));
		builder.put(ModelLayers.DOUBLE_CHEST_LEFT, ChestModel.createDoubleBodyLeftLayer());
		builder.put(ModelLayers.DOUBLE_CHEST_RIGHT, ChestModel.createDoubleBodyRightLayer());
		builder.put(ModelLayers.DRAGON_SKULL, DragonHeadModel.createHeadLayer());
		builder.put(ModelLayers.DROWNED, layerDefinition49);
		ModelLayers.DROWNED_ARMOR.putFrom(armorModelSet, builder);
		builder.put(ModelLayers.DROWNED_OUTER_LAYER, layerDefinition50);
		builder.put(ModelLayers.DROWNED_BABY, layerDefinition49.apply(HumanoidModel.BABY_TRANSFORMER));
		ModelLayers.DROWNED_BABY_ARMOR.putFrom(armorModelSet2, builder);
		builder.put(ModelLayers.DROWNED_BABY_OUTER_LAYER, layerDefinition50.apply(HumanoidModel.BABY_TRANSFORMER));
		builder.put(ModelLayers.ELDER_GUARDIAN, GuardianModel.createElderGuardianLayer());
		builder.put(ModelLayers.ELYTRA, layerDefinition15);
		builder.put(ModelLayers.ELYTRA_BABY, layerDefinition15.apply(ElytraModel.BABY_TRANSFORMER));
		builder.put(ModelLayers.ENDERMAN, EndermanModel.createBodyLayer());
		builder.put(ModelLayers.ENDERMITE, EndermiteModel.createBodyLayer());
		builder.put(ModelLayers.ENDER_DRAGON, EnderDragonModel.createBodyLayer());
		builder.put(ModelLayers.END_CRYSTAL, EndCrystalModel.createBodyLayer());
		builder.put(ModelLayers.EVOKER, layerDefinition8);
		builder.put(ModelLayers.EVOKER_FANGS, EvokerFangsModel.createBodyLayer());
		builder.put(ModelLayers.FOX, FoxModel.createBodyLayer());
		builder.put(ModelLayers.FOX_BABY, FoxModel.createBodyLayer().apply(FoxModel.BABY_TRANSFORMER));
		builder.put(ModelLayers.FROG, FrogModel.createBodyLayer());
		builder.put(ModelLayers.FURNACE_MINECART, layerDefinition2);
		builder.put(ModelLayers.GHAST, GhastModel.createBodyLayer());
		MeshTransformer meshTransformer2 = MeshTransformer.scaling(6.0F);
		builder.put(ModelLayers.GIANT, layerDefinition.apply(meshTransformer2));
		ModelLayers.GIANT_ARMOR.putFrom(armorModelSet.map(layerDefinitionx -> layerDefinitionx.apply(meshTransformer2)), builder);
		builder.put(ModelLayers.GLOW_SQUID, layerDefinition51);
		builder.put(ModelLayers.GLOW_SQUID_BABY, layerDefinition51.apply(SquidModel.BABY_TRANSFORMER));
		builder.put(ModelLayers.GOAT, layerDefinition35);
		builder.put(ModelLayers.GOAT_BABY, layerDefinition35.apply(GoatModel.BABY_TRANSFORMER));
		builder.put(ModelLayers.GUARDIAN, GuardianModel.createBodyLayer());
		builder.put(ModelLayers.HAPPY_GHAST, HappyGhastModel.createBodyLayer(false, CubeDeformation.NONE));
		builder.put(ModelLayers.HAPPY_GHAST_BABY, HappyGhastModel.createBodyLayer(true, CubeDeformation.NONE).apply(HappyGhastModel.BABY_TRANSFORMER));
		builder.put(ModelLayers.HAPPY_GHAST_HARNESS, HappyGhastHarnessModel.createHarnessLayer(false));
		builder.put(ModelLayers.HAPPY_GHAST_BABY_HARNESS, HappyGhastHarnessModel.createHarnessLayer(true).apply(HappyGhastModel.BABY_TRANSFORMER));
		builder.put(ModelLayers.HAPPY_GHAST_ROPES, HappyGhastModel.createBodyLayer(false, new CubeDeformation(0.2F)));
		builder.put(ModelLayers.HAPPY_GHAST_BABY_ROPES, HappyGhastModel.createBodyLayer(true, new CubeDeformation(0.2F)).apply(HappyGhastModel.BABY_TRANSFORMER));
		builder.put(ModelLayers.HOGLIN, layerDefinition25);
		builder.put(ModelLayers.HOGLIN_BABY, layerDefinition26);
		builder.put(ModelLayers.HOPPER_MINECART, layerDefinition2);
		MeshTransformer meshTransformer3 = MeshTransformer.scaling(1.1F);
		builder.put(ModelLayers.HORSE, layerDefinition4.apply(meshTransformer3));
		builder.put(ModelLayers.HORSE_BABY, layerDefinition5.apply(meshTransformer3));
		builder.put(ModelLayers.HORSE_ARMOR, LayerDefinition.create(AbstractEquineModel.createBodyMesh(new CubeDeformation(0.1F)), 64, 64).apply(meshTransformer3));
		builder.put(
			ModelLayers.HORSE_BABY_ARMOR, LayerDefinition.create(AbstractEquineModel.createBabyMesh(new CubeDeformation(0.1F)), 64, 64).apply(meshTransformer3)
		);
		builder.put(ModelLayers.HORSE_SADDLE, layerDefinition6.apply(meshTransformer3));
		builder.put(ModelLayers.HORSE_BABY_SADDLE, layerDefinition7.apply(meshTransformer3));
		MeshTransformer meshTransformer4 = MeshTransformer.scaling(1.0625F);
		builder.put(ModelLayers.HUSK, layerDefinition.apply(meshTransformer4));
		ModelLayers.HUSK_ARMOR.putFrom(armorModelSet.map(layerDefinitionx -> layerDefinitionx.apply(meshTransformer4)), builder);
		builder.put(ModelLayers.HUSK_BABY, layerDefinition.apply(HumanoidModel.BABY_TRANSFORMER).apply(meshTransformer4));
		ModelLayers.HUSK_BABY_ARMOR.putFrom(armorModelSet2.map(layerDefinitionx -> layerDefinitionx.apply(meshTransformer4)), builder);
		builder.put(ModelLayers.ILLUSIONER, layerDefinition8);
		builder.put(ModelLayers.IRON_GOLEM, IronGolemModel.createBodyLayer());
		builder.put(ModelLayers.LEASH_KNOT, LeashKnotModel.createBodyLayer());
		builder.put(ModelLayers.LLAMA, layerDefinition22);
		builder.put(ModelLayers.LLAMA_BABY, layerDefinition22.apply(LlamaModel.BABY_TRANSFORMER));
		builder.put(ModelLayers.LLAMA_DECOR, layerDefinition23);
		builder.put(ModelLayers.LLAMA_BABY_DECOR, layerDefinition23.apply(LlamaModel.BABY_TRANSFORMER));
		builder.put(ModelLayers.LLAMA_SPIT, LlamaSpitModel.createBodyLayer());
		builder.put(ModelLayers.MAGMA_CUBE, MagmaCubeModel.createBodyLayer());
		builder.put(ModelLayers.MINECART, layerDefinition2);
		builder.put(ModelLayers.MOOSHROOM, layerDefinition11);
		builder.put(ModelLayers.MOOSHROOM_BABY, layerDefinition11.apply(CowModel.BABY_TRANSFORMER));
		builder.put(ModelLayers.MULE, DonkeyModel.createBodyLayer(0.92F));
		builder.put(ModelLayers.MULE_BABY, DonkeyModel.createBabyLayer(0.92F));
		builder.put(ModelLayers.MULE_SADDLE, DonkeyModel.createSaddleLayer(0.92F, false));
		builder.put(ModelLayers.MULE_BABY_SADDLE, DonkeyModel.createSaddleLayer(0.92F, true));
		builder.put(ModelLayers.NAUTILUS, NautilusModel.createBodyLayer());
		builder.put(ModelLayers.NAUTILUS_BABY, NautilusModel.createBabyBodyLayer());
		builder.put(ModelLayers.NAUTILUS_SADDLE, layerDefinition54);
		builder.put(ModelLayers.NAUTILUS_ARMOR, NautilusArmorModel.createBodyLayer());
		builder.put(ModelLayers.ZOMBIE_NAUTILUS, NautilusModel.createBodyLayer());
		builder.put(ModelLayers.ZOMBIE_NAUTILUS_CORAL, ZombieNautilusCoralModel.createBodyLayer());
		builder.put(ModelLayers.OCELOT, layerDefinition16);
		builder.put(ModelLayers.OCELOT_BABY, layerDefinition17);
		builder.put(ModelLayers.PANDA, layerDefinition36);
		builder.put(ModelLayers.PANDA_BABY, layerDefinition36.apply(PandaModel.BABY_TRANSFORMER));
		builder.put(ModelLayers.PARCHED, SkeletonModel.createSingleModelDualBodyLayer());
		ModelLayers.PARCHED_ARMOR.putFrom(armorModelSet, builder);
		builder.put(ModelLayers.PARCHED_OUTER_LAYER, LayerDefinition.create(HumanoidModel.createMesh(new CubeDeformation(0.25F), 0.0F), 64, 32));
		builder.put(ModelLayers.PARROT, ParrotModel.createBodyLayer());
		builder.put(ModelLayers.PHANTOM, PhantomModel.createBodyLayer());
		builder.put(ModelLayers.PIG, layerDefinition37);
		builder.put(ModelLayers.PIG_BABY, layerDefinition37.apply(PigModel.BABY_TRANSFORMER));
		builder.put(ModelLayers.PIG_SADDLE, layerDefinition38);
		builder.put(ModelLayers.PIG_BABY_SADDLE, layerDefinition38.apply(PigModel.BABY_TRANSFORMER));
		builder.put(ModelLayers.PIGLIN, layerDefinition19);
		ModelLayers.PIGLIN_ARMOR.putFrom(armorModelSet4, builder);
		builder.put(ModelLayers.PIGLIN_BRUTE, layerDefinition19);
		ModelLayers.PIGLIN_BRUTE_ARMOR.putFrom(armorModelSet4, builder);
		builder.put(ModelLayers.PIGLIN_BABY, layerDefinition19.apply(HumanoidModel.BABY_TRANSFORMER));
		ModelLayers.PIGLIN_BABY_ARMOR.putFrom(armorModelSet5, builder);
		builder.put(ModelLayers.PIGLIN_HEAD, layerDefinition20);
		builder.put(ModelLayers.PILLAGER, layerDefinition8);
		builder.put(ModelLayers.PLAYER, LayerDefinition.create(PlayerModel.createMesh(CubeDeformation.NONE, false), 64, 64));
		builder.put(ModelLayers.PLAYER_EARS, PlayerEarsModel.createEarsLayer());
		builder.put(ModelLayers.PLAYER_CAPE, PlayerCapeModel.createCapeLayer());
		builder.put(ModelLayers.PLAYER_HEAD, layerDefinition21);
		ModelLayers.PLAYER_ARMOR.putFrom(armorModelSet3, builder);
		builder.put(ModelLayers.PLAYER_SLIM, LayerDefinition.create(PlayerModel.createMesh(CubeDeformation.NONE, true), 64, 64));
		ModelLayers.PLAYER_SLIM_ARMOR.putFrom(armorModelSet3, builder);
		builder.put(ModelLayers.PLAYER_SPIN_ATTACK, SpinAttackEffectModel.createLayer());
		builder.put(ModelLayers.POLAR_BEAR, PolarBearModel.createBodyLayer(false));
		builder.put(ModelLayers.POLAR_BEAR_BABY, PolarBearModel.createBodyLayer(true));
		builder.put(ModelLayers.PUFFERFISH_BIG, PufferfishBigModel.createBodyLayer());
		builder.put(ModelLayers.PUFFERFISH_MEDIUM, PufferfishMidModel.createBodyLayer());
		builder.put(ModelLayers.PUFFERFISH_SMALL, PufferfishSmallModel.createBodyLayer());
		builder.put(ModelLayers.RABBIT, RabbitModel.createBodyLayer(false));
		builder.put(ModelLayers.RABBIT_BABY, RabbitModel.createBodyLayer(true));
		builder.put(ModelLayers.RAVAGER, RavagerModel.createBodyLayer());
		builder.put(ModelLayers.SALMON, layerDefinition53);
		builder.put(ModelLayers.SALMON_SMALL, layerDefinition53.apply(SalmonModel.SMALL_TRANSFORMER));
		builder.put(ModelLayers.SALMON_LARGE, layerDefinition53.apply(SalmonModel.LARGE_TRANSFORMER));
		builder.put(ModelLayers.SHEEP, layerDefinition39);
		builder.put(ModelLayers.SHEEP_BABY, layerDefinition39.apply(SheepModel.BABY_TRANSFORMER));
		builder.put(ModelLayers.SHEEP_WOOL, layerDefinition40);
		builder.put(ModelLayers.SHEEP_BABY_WOOL, layerDefinition40.apply(SheepModel.BABY_TRANSFORMER));
		builder.put(ModelLayers.SHEEP_WOOL_UNDERCOAT, layerDefinition39);
		builder.put(ModelLayers.SHEEP_BABY_WOOL_UNDERCOAT, layerDefinition39.apply(SheepModel.BABY_TRANSFORMER));
		builder.put(ModelLayers.SHIELD, ShieldModel.createLayer());
		builder.put(ModelLayers.SHULKER, ShulkerModel.createBodyLayer());
		builder.put(ModelLayers.SHULKER_BOX, ShulkerModel.createBoxLayer());
		builder.put(ModelLayers.SHULKER_BULLET, ShulkerBulletModel.createBodyLayer());
		builder.put(ModelLayers.SILVERFISH, SilverfishModel.createBodyLayer());
		builder.put(ModelLayers.SKELETON, layerDefinition27);
		ModelLayers.SKELETON_ARMOR.putFrom(armorModelSet, builder);
		builder.put(ModelLayers.SKELETON_HORSE, layerDefinition4);
		builder.put(ModelLayers.SKELETON_HORSE_BABY, layerDefinition5);
		builder.put(ModelLayers.SKELETON_HORSE_SADDLE, layerDefinition6);
		builder.put(ModelLayers.SKELETON_HORSE_BABY_SADDLE, layerDefinition7);
		builder.put(ModelLayers.SKELETON_SKULL, layerDefinition3);
		builder.put(ModelLayers.SLIME, SlimeModel.createInnerBodyLayer());
		builder.put(ModelLayers.SLIME_OUTER, SlimeModel.createOuterBodyLayer());
		builder.put(ModelLayers.SNIFFER, layerDefinition41);
		builder.put(ModelLayers.SNIFFER_BABY, layerDefinition41.apply(SnifferModel.BABY_TRANSFORMER));
		builder.put(ModelLayers.SNOW_GOLEM, SnowGolemModel.createBodyLayer());
		builder.put(ModelLayers.SPAWNER_MINECART, layerDefinition2);
		builder.put(ModelLayers.SPIDER, layerDefinition30);
		builder.put(ModelLayers.SQUID, layerDefinition51);
		builder.put(ModelLayers.SQUID_BABY, layerDefinition51.apply(SquidModel.BABY_TRANSFORMER));
		builder.put(ModelLayers.STRAY, layerDefinition27);
		ModelLayers.STRAY_ARMOR.putFrom(armorModelSet, builder);
		builder.put(ModelLayers.STRAY_OUTER_LAYER, LayerDefinition.create(HumanoidModel.createMesh(new CubeDeformation(0.25F), 0.0F), 64, 32));
		builder.put(ModelLayers.STRIDER, layerDefinition24);
		builder.put(ModelLayers.STRIDER_SADDLE, layerDefinition24);
		builder.put(ModelLayers.STRIDER_BABY, layerDefinition24.apply(StriderModel.BABY_TRANSFORMER));
		builder.put(ModelLayers.STRIDER_BABY_SADDLE, layerDefinition24.apply(StriderModel.BABY_TRANSFORMER));
		builder.put(ModelLayers.TADPOLE, TadpoleModel.createBodyLayer());
		builder.put(ModelLayers.TNT_MINECART, layerDefinition2);
		builder.put(ModelLayers.TRADER_LLAMA, layerDefinition22);
		builder.put(ModelLayers.TRADER_LLAMA_BABY, layerDefinition22.apply(LlamaModel.BABY_TRANSFORMER));
		builder.put(ModelLayers.TRIDENT, TridentModel.createLayer());
		builder.put(ModelLayers.TROPICAL_FISH_LARGE, TropicalFishLargeModel.createBodyLayer(CubeDeformation.NONE));
		builder.put(ModelLayers.TROPICAL_FISH_LARGE_PATTERN, TropicalFishLargeModel.createBodyLayer(FISH_PATTERN_DEFORMATION));
		builder.put(ModelLayers.TROPICAL_FISH_SMALL, TropicalFishSmallModel.createBodyLayer(CubeDeformation.NONE));
		builder.put(ModelLayers.TROPICAL_FISH_SMALL_PATTERN, TropicalFishSmallModel.createBodyLayer(FISH_PATTERN_DEFORMATION));
		builder.put(ModelLayers.TURTLE, layerDefinition42);
		builder.put(ModelLayers.TURTLE_BABY, layerDefinition42.apply(TurtleModel.BABY_TRANSFORMER));
		builder.put(ModelLayers.UNDEAD_HORSE_ARMOR, LayerDefinition.create(AbstractEquineModel.createBodyMesh(new CubeDeformation(0.1F)), 64, 64));
		builder.put(ModelLayers.UNDEAD_HORSE_BABY_ARMOR, LayerDefinition.create(AbstractEquineModel.createBabyMesh(new CubeDeformation(0.1F)), 64, 64));
		builder.put(ModelLayers.VEX, VexModel.createBodyLayer());
		builder.put(ModelLayers.VILLAGER, layerDefinition28);
		builder.put(ModelLayers.VILLAGER_NO_HAT, layerDefinition29);
		builder.put(ModelLayers.VILLAGER_BABY, layerDefinition28.apply(VillagerModel.BABY_TRANSFORMER));
		builder.put(ModelLayers.VILLAGER_BABY_NO_HAT, layerDefinition29.apply(VillagerModel.BABY_TRANSFORMER));
		builder.put(ModelLayers.VINDICATOR, layerDefinition8);
		builder.put(ModelLayers.WARDEN, WardenModel.createBodyLayer());
		builder.put(ModelLayers.WARDEN_TENDRILS, WardenModel.createTendrilsLayer());
		builder.put(ModelLayers.WARDEN_HEART, WardenModel.createHeartLayer());
		builder.put(ModelLayers.WARDEN_BIOLUMINESCENT, WardenModel.createBioluminescentLayer());
		builder.put(ModelLayers.WARDEN_PULSATING_SPOTS, WardenModel.createPulsatingSpotsLayer());
		builder.put(ModelLayers.WARM_COW, layerDefinition43);
		builder.put(ModelLayers.WARM_COW_BABY, layerDefinition43.apply(CowModel.BABY_TRANSFORMER));
		builder.put(ModelLayers.WANDERING_TRADER, layerDefinition28);
		builder.put(ModelLayers.WIND_CHARGE, WindChargeModel.createBodyLayer());
		builder.put(ModelLayers.WITCH, WitchModel.createBodyLayer().apply(meshTransformer));
		builder.put(ModelLayers.WITHER, WitherBossModel.createBodyLayer(CubeDeformation.NONE));
		builder.put(ModelLayers.WITHER_ARMOR, WitherBossModel.createBodyLayer(INNER_ARMOR_DEFORMATION));
		builder.put(ModelLayers.WITHER_SKULL, WitherSkullRenderer.createSkullLayer());
		MeshTransformer meshTransformer5 = MeshTransformer.scaling(1.2F);
		builder.put(ModelLayers.WITHER_SKELETON, layerDefinition27.apply(meshTransformer5));
		ModelLayers.WITHER_SKELETON_ARMOR.putFrom(armorModelSet.map(layerDefinitionx -> layerDefinitionx.apply(meshTransformer5)), builder);
		builder.put(ModelLayers.WITHER_SKELETON_SKULL, layerDefinition3);
		builder.put(ModelLayers.WOLF, layerDefinition44);
		builder.put(ModelLayers.WOLF_ARMOR, layerDefinition45);
		builder.put(ModelLayers.WOLF_BABY, layerDefinition44.apply(WolfModel.BABY_TRANSFORMER));
		builder.put(ModelLayers.WOLF_BABY_ARMOR, layerDefinition45.apply(WolfModel.BABY_TRANSFORMER));
		builder.put(ModelLayers.ZOGLIN, layerDefinition25);
		builder.put(ModelLayers.ZOGLIN_BABY, layerDefinition26);
		builder.put(ModelLayers.ZOMBIE, layerDefinition);
		ModelLayers.ZOMBIE_ARMOR.putFrom(armorModelSet, builder);
		builder.put(ModelLayers.ZOMBIE_BABY, layerDefinition.apply(HumanoidModel.BABY_TRANSFORMER));
		ModelLayers.ZOMBIE_BABY_ARMOR.putFrom(armorModelSet2, builder);
		builder.put(ModelLayers.ZOMBIE_HEAD, layerDefinition21);
		builder.put(ModelLayers.ZOMBIE_HORSE, layerDefinition4);
		builder.put(ModelLayers.ZOMBIE_HORSE_BABY, layerDefinition5);
		builder.put(ModelLayers.ZOMBIE_HORSE_SADDLE, layerDefinition6);
		builder.put(ModelLayers.ZOMBIE_HORSE_BABY_SADDLE, layerDefinition7);
		builder.put(ModelLayers.ZOMBIE_VILLAGER, layerDefinition46);
		builder.put(ModelLayers.ZOMBIE_VILLAGER_NO_HAT, layerDefinition47);
		ArmorModelSet<LayerDefinition> armorModelSet7 = ZombieVillagerModel.createArmorLayerSet(INNER_ARMOR_DEFORMATION, OUTER_ARMOR_DEFORMATION);
		ModelLayers.ZOMBIE_VILLAGER_ARMOR.putFrom(armorModelSet7, builder);
		builder.put(ModelLayers.ZOMBIE_VILLAGER_BABY, layerDefinition46.apply(HumanoidModel.BABY_TRANSFORMER));
		builder.put(ModelLayers.ZOMBIE_VILLAGER_BABY_NO_HAT, layerDefinition47.apply(HumanoidModel.BABY_TRANSFORMER));
		ModelLayers.ZOMBIE_VILLAGER_BABY_ARMOR.putFrom(armorModelSet7.map(layerDefinitionx -> layerDefinitionx.apply(HumanoidModel.BABY_TRANSFORMER)), builder);
		builder.put(ModelLayers.ZOMBIFIED_PIGLIN, layerDefinition19);
		ModelLayers.ZOMBIFIED_PIGLIN_ARMOR.putFrom(armorModelSet4, builder);
		builder.put(ModelLayers.ZOMBIFIED_PIGLIN_BABY, layerDefinition19.apply(HumanoidModel.BABY_TRANSFORMER));
		ModelLayers.ZOMBIFIED_PIGLIN_BABY_ARMOR.putFrom(armorModelSet5, builder);
		builder.put(ModelLayers.BAMBOO_RAFT, RaftModel.createRaftModel());
		builder.put(ModelLayers.BAMBOO_CHEST_RAFT, RaftModel.createChestRaftModel());
		LayerDefinition layerDefinition55 = BoatModel.createBoatModel();
		LayerDefinition layerDefinition56 = BoatModel.createChestBoatModel();
		builder.put(ModelLayers.OAK_BOAT, layerDefinition55);
		builder.put(ModelLayers.OAK_CHEST_BOAT, layerDefinition56);
		builder.put(ModelLayers.SPRUCE_BOAT, layerDefinition55);
		builder.put(ModelLayers.SPRUCE_CHEST_BOAT, layerDefinition56);
		builder.put(ModelLayers.BIRCH_BOAT, layerDefinition55);
		builder.put(ModelLayers.BIRCH_CHEST_BOAT, layerDefinition56);
		builder.put(ModelLayers.JUNGLE_BOAT, layerDefinition55);
		builder.put(ModelLayers.JUNGLE_CHEST_BOAT, layerDefinition56);
		builder.put(ModelLayers.ACACIA_BOAT, layerDefinition55);
		builder.put(ModelLayers.ACACIA_CHEST_BOAT, layerDefinition56);
		builder.put(ModelLayers.CHERRY_BOAT, layerDefinition55);
		builder.put(ModelLayers.CHERRY_CHEST_BOAT, layerDefinition56);
		builder.put(ModelLayers.DARK_OAK_BOAT, layerDefinition55);
		builder.put(ModelLayers.DARK_OAK_CHEST_BOAT, layerDefinition56);
		builder.put(ModelLayers.PALE_OAK_BOAT, layerDefinition55);
		builder.put(ModelLayers.PALE_OAK_CHEST_BOAT, layerDefinition56);
		builder.put(ModelLayers.MANGROVE_BOAT, layerDefinition55);
		builder.put(ModelLayers.MANGROVE_CHEST_BOAT, layerDefinition56);
		LayerDefinition layerDefinition57 = SignRenderer.createSignLayer(true);
		LayerDefinition layerDefinition58 = SignRenderer.createSignLayer(false);
		WoodType.values().forEach(woodType -> {
			builder.put(ModelLayers.createStandingSignModelName(woodType), layerDefinition57);
			builder.put(ModelLayers.createWallSignModelName(woodType), layerDefinition58);

			for (HangingSignRenderer.AttachmentType attachmentType : HangingSignRenderer.AttachmentType.values()) {
				LayerDefinition layerDefinition3x = HangingSignRenderer.createHangingSignLayer(attachmentType);
				builder.put(ModelLayers.createHangingSignModelName(woodType, attachmentType), layerDefinition3x);
			}
		});
		ImmutableMap<ModelLayerLocation, LayerDefinition> immutableMap = builder.build();
		List<ModelLayerLocation> list = ModelLayers.getKnownLocations().filter(modelLayerLocation -> !immutableMap.containsKey(modelLayerLocation)).toList();
		if (!list.isEmpty()) {
			throw new IllegalStateException("Missing layer definitions: " + list);
		} else {
			return immutableMap;
		}
	}
}
